import { useEffect, useRef, useState } from 'react';
import { action, safeLink, stages, displayDate as date, type Opportunity } from '../services/command';
import { ApplicationPack } from './ApplicationPack';

export function ActionDrawer({ job, disabled, busy, close, run, transition, saved }: { job: Opportunity; disabled: boolean; busy: boolean; close: () => void; run: (kind: string, id: string) => Promise<void>; transition: (job: Opportunity, stage: string) => Promise<void>; saved: () => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [name, setName] = useState(''); const [note, setNote] = useState(''); const [evidence, setEvidence] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { dialog.current?.showModal(); }, []);
  const fallback = ({ Discovered: 'Evaluate the live posting to generate a report before deciding whether to apply.', Evaluated: 'Review the report and draft, then open the employer posting. Mark Applied only after you submit.', Applied: 'Record any employer reply or actual contact below. Move to Screen/Interview when one is scheduled.', 'Screen/Interview': 'Review the report and prepare examples from your experience. Record interview notes below.', Offer: 'Review the written offer and your questions before making a decision.', Archived: 'This role is archived. Change its stage if you want to revisit it.' } as Record<string, string>)[job.stage];
  return <dialog ref={dialog} className="drawer" onCancel={close} aria-label={`Application details: ${job.company}`} aria-labelledby="drawer-title"><div className="drawer-top"><span className="eyebrow">DIRECT ACTION / {job.company}</span><button onClick={close} aria-label="Close details">×</button></div><h2 id="drawer-title">{job.role}</h2><p>{job.location}</p><span className={`tier ${job.tier}`}>{job.tier} / {job.triagePercent}% priority</span><p>{job.rationale}</p><div className="toolbar">{safeLink(job.url) && <a href={safeLink(job.url)} target="_blank" rel="noreferrer">Open employer posting ↗</a>}<button disabled={disabled} onClick={() => void run('evaluate', job.id)}>Evaluate role</button><button disabled={disabled} onClick={() => void run('strategy', job.id)}>Research & draft</button></div><ApplicationPack job={job}/><label>Application stage<select aria-label="Application stage" value={job.stage} disabled={busy} onChange={e => void transition(job, e.target.value)}>{stages.map(s => <option key={s} disabled={(s === 'Evaluated' && !job.report) || (s === 'Discovered' && !!job.trackerNumber)}>{s}</option>)}</select></label><h3>Recommended next step</h3><p>{job.nextAction || fallback}</p><details><summary>Evaluation report {job.evaluationScore ? `/ ${job.evaluationScore} out of 5` : '/ not yet available'}</summary><pre>{job.report || 'No evaluation report saved for this opportunity.'}</pre></details><details><summary>Employer draft preview</summary><pre>{job.draft || 'No employer strategy draft saved. Use Research & draft to create one with verified sources.'}</pre></details><h3>Contact / referral log</h3><form onSubmit={async e => { e.preventDefault(); setSaving(true); try { await action('contact', { jobId: job.id, name, note, evidence }); setNote(''); setError('Contact note saved.'); await saved(); } catch (err) { setError(String(err)); } finally { setSaving(false); } }}><label>Actual contact name<input aria-label="Actual contact name" required maxLength={200} value={name} onChange={e => setName(e.target.value)}/></label><label>Evidence / referral source URL<input aria-label="Evidence / referral source URL" type="url" value={evidence} onChange={e => setEvidence(e.target.value)}/></label><label>Conversation or referral note<textarea aria-label="Conversation or referral note" required maxLength={4000} value={note} onChange={e => setNote(e.target.value)}/></label><button disabled={busy || saving}>Save contact note</button><p role="status">{error}</p></form><h3>Audit history</h3>{!job.events.length && <p>No command-center events yet. Original tracker date: {job.date || 'unknown'}.</p>}{job.events.map(e => <article className="audit" key={e.id}><small>{date(e.timestamp)} / {e.kind}</small><p>{Object.entries(e.payload).map(([key, value]) => `${key}: ${value}`).join(' · ')}</p></article>)}</dialog>;
}
